In [67]:
# Dependencies
import pandas as pd

# **ETL: Data Extraction**

In [68]:
# Store filepath in a variable
file = "/content/Data.csv"

In [69]:
# Read our Data file with the pandas library
df = pd.read_csv(file)

In [70]:
# Show header
df.head()

Season(1-Winter, 2-Spring, 3-Summer, 4-Fall)  \
0                                         -0.33   
1                                         -0.33   
2                                         -0.33   
3                                         -0.33   
4                                         -0.33   

   Age at the time of analysis. 18-36 (0, 1)  \
0                                       0.69   
1                                       0.94   
2                                       0.50   
3                                       0.75   
4                                       0.67   

   Childish diseases (ie , chicken pox, measles, mumps, polio) 1) yes, 2) no.  \
0                                                  0                            
1                                                  1                            
2                                                  1                            
3                                                  0                            
4                                                  1                            

   Accident or serious trauma 1) yes, 2) no.  \
0                                          1   
1                                          0   
2                                          0   
3                                          1   
4                                          1   

   Surgical intervention 1) yes, 2) no.  \
0                                     1   
1                                     1   
2                                     0   
3                                     1   
4                                     0   

   High fevers in the last year 1) less than three months ago, 2) more than three months ago, 3) no  \
0                                                  0                                                  
1                                                  0                                                  
2                                                  0                                                  
3                                                  0                                                  
4                                                  0                                                  

   Frequency of alcohol consumption 1) several times a day, 2) every day, 3) several times a week, 4) once a week, 5) hardly ever or never  \
0                                                0.8                                                                                         
1                                                0.8                                                                                         
2                                                1.0                                                                                         
3                                                1.0                                                                                         
4                                                0.8                                                                                         

   Smoking habit 1) never, 2) occasional 3) daily.  \
0                                                0   
1                                                1   
2                                               -1   
3                                               -1   
4                                               -1   

   Number of hours spent sitting per day ene-16  \
0                                          0.88   
1                                          0.31   
2                                          0.50   
3                                          0.38   
4                                          0.50   

   Output Diagnosis(0-Normal, 1-Altered)  
0                                      0  
1                                      1  
2                                      0  
3                                      0  
4                                      1

In [71]:
# Change column names
df.columns = ['season', 'age', 'diseases', 'accident', 'surgery', 'fever', 'alcohol', 'smoking', 'sitting', 'diagnosis']

In [72]:
df.head()


season   age  diseases  accident  surgery  fever  alcohol  smoking  \
0   -0.33  0.69         0         1        1      0      0.8        0   
1   -0.33  0.94         1         0        1      0      0.8        1   
2   -0.33  0.50         1         0        0      0      1.0       -1   
3   -0.33  0.75         0         1        1      0      1.0       -1   
4   -0.33  0.67         1         1        0      0      0.8       -1   

   sitting  diagnosis  
0     0.88          0  
1     0.31          1  
2     0.50          0  
3     0.38          0  
4     0.50          1

# **ETL: Data Transformation**

In [73]:
#splitting fever column
df_one = pd.get_dummies(df, columns=['fever'], prefix = ['fever'])
df_one.head()

season   age  diseases  accident  surgery  alcohol  smoking  sitting  \
0   -0.33  0.69         0         1        1      0.8        0     0.88   
1   -0.33  0.94         1         0        1      0.8        1     0.31   
2   -0.33  0.50         1         0        0      1.0       -1     0.50   
3   -0.33  0.75         0         1        1      1.0       -1     0.38   
4   -0.33  0.67         1         1        0      0.8       -1     0.50   

   diagnosis  fever_-1  fever_0  fever_1  
0          0     False     True    False  
1          1     False     True    False  
2          0     False     True    False  
3          0     False     True    False  
4          1     False     True    False

In [74]:
#splitting alcohol column
df_two = pd.get_dummies(df_one, columns=['alcohol'], prefix = ['alcohol'])
df_two.head()

season   age  diseases  accident  surgery  smoking  sitting  diagnosis  \
0   -0.33  0.69         0         1        1        0     0.88          0   
1   -0.33  0.94         1         0        1        1     0.31          1   
2   -0.33  0.50         1         0        0       -1     0.50          0   
3   -0.33  0.75         0         1        1       -1     0.38          0   
4   -0.33  0.67         1         1        0       -1     0.50          1   

   fever_-1  fever_0  fever_1  alcohol_0.2  alcohol_0.4  alcohol_0.6  \
0     False     True    False        False        False        False   
1     False     True    False        False        False        False   
2     False     True    False        False        False        False   
3     False     True    False        False        False        False   
4     False     True    False        False        False        False   

   alcohol_0.8  alcohol_1.0  
0         True        False  
1         True        False  
2        False         True  
3        False         True  
4         True        False

In [75]:
#splitting smoking column
df_three = pd.get_dummies(df_two, columns=['smoking'], prefix = ['smoking'])
df_three.head()

season   age  diseases  accident  surgery  sitting  diagnosis  fever_-1  \
0   -0.33  0.69         0         1        1     0.88          0     False   
1   -0.33  0.94         1         0        1     0.31          1     False   
2   -0.33  0.50         1         0        0     0.50          0     False   
3   -0.33  0.75         0         1        1     0.38          0     False   
4   -0.33  0.67         1         1        0     0.50          1     False   

   fever_0  fever_1  alcohol_0.2  alcohol_0.4  alcohol_0.6  alcohol_0.8  \
0     True    False        False        False        False         True   
1     True    False        False        False        False         True   
2     True    False        False        False        False        False   
3     True    False        False        False        False        False   
4     True    False        False        False        False         True   

   alcohol_1.0  smoking_-1  smoking_0  smoking_1  
0        False       False       True      False  
1        False       False      False       True  
2         True        True      False      False  
3         True        True      False      False  
4        False        True      False      False

In [76]:
df_three.loc[df_three['sitting'] > 0.5, 'sitting'] = 1

In [77]:
df_three.head()

season   age  diseases  accident  surgery  sitting  diagnosis  fever_-1  \
0   -0.33  0.69         0         1        1     1.00          0     False   
1   -0.33  0.94         1         0        1     0.31          1     False   
2   -0.33  0.50         1         0        0     0.50          0     False   
3   -0.33  0.75         0         1        1     0.38          0     False   
4   -0.33  0.67         1         1        0     0.50          1     False   

   fever_0  fever_1  alcohol_0.2  alcohol_0.4  alcohol_0.6  alcohol_0.8  \
0     True    False        False        False        False         True   
1     True    False        False        False        False         True   
2     True    False        False        False        False        False   
3     True    False        False        False        False        False   
4     True    False        False        False        False         True   

   alcohol_1.0  smoking_-1  smoking_0  smoking_1  
0        False       False       True      False  
1        False       False      False       True  
2         True        True      False      False  
3         True        True      False      False  
4        False        True      False      False

In [78]:
df_four = pd.get_dummies(df_three, columns=['sitting'], prefix = ['sitting'])

In [79]:
df_five = pd.get_dummies(df_four, columns=['season'], prefix = ['season'])

In [80]:
df_five.loc[df_five['age'] > 0.5, 'age'] = 1

In [81]:
df_five.loc[df_five['age'] <= 0.5, 'age'] = 0.5

In [82]:
df_five.head()

age  diseases  accident  surgery  diagnosis  fever_-1  fever_0  fever_1  \
0  1.0         0         1        1          0     False     True    False   
1  1.0         1         0        1          1     False     True    False   
2  0.5         1         0        0          0     False     True    False   
3  1.0         0         1        1          0     False     True    False   
4  1.0         1         1        0          1     False     True    False   

   alcohol_0.2  alcohol_0.4  ...  sitting_0.31  sitting_0.38  sitting_0.44  \
0        False        False  ...         False         False         False   
1        False        False  ...          True         False         False   
2        False        False  ...         False         False         False   
3        False        False  ...         False          True         False   
4        False        False  ...         False         False         False   

   sitting_0.47  sitting_0.5  sitting_1.0  season_-1.0  season_-0.33  \
0         False        False         True        False          True   
1         False        False        False        False          True   
2         False         True        False        False          True   
3         False        False        False        False          True   
4         False         True        False        False          True   

   season_0.33  season_1.0  
0        False       False  
1        False       False  
2        False       False  
3        False       False  
4        False       False  

[5 rows x 30 columns]

In [83]:
df_six = pd.get_dummies(df_five, columns=['age'], prefix = ['age'])

In [84]:
df_six.head()

diseases  accident  surgery  diagnosis  fever_-1  fever_0  fever_1  \
0         0         1        1          0     False     True    False   
1         1         0        1          1     False     True    False   
2         1         0        0          0     False     True    False   
3         0         1        1          0     False     True    False   
4         1         1        0          1     False     True    False   

   alcohol_0.2  alcohol_0.4  alcohol_0.6  ...  sitting_0.44  sitting_0.47  \
0        False        False        False  ...         False         False   
1        False        False        False  ...         False         False   
2        False        False        False  ...         False         False   
3        False        False        False  ...         False         False   
4        False        False        False  ...         False         False   

   sitting_0.5  sitting_1.0  season_-1.0  season_-0.33  season_0.33  \
0        False         True        False          True        False   
1        False        False        False          True        False   
2         True        False        False          True        False   
3        False        False        False          True        False   
4         True        False        False          True        False   

   season_1.0  age_0.5  age_1.0  
0       False    False     True  
1       False    False     True  
2       False     True    False  
3       False    False     True  
4       False    False     True  

[5 rows x 31 columns]

In [85]:
df_six.columns

Index(['diseases', 'accident', 'surgery', 'diagnosis', 'fever_-1', 'fever_0',
       'fever_1', 'alcohol_0.2', 'alcohol_0.4', 'alcohol_0.6', 'alcohol_0.8',
       'alcohol_1.0', 'smoking_-1', 'smoking_0', 'smoking_1', 'sitting_0.06',
       'sitting_0.13', 'sitting_0.19', 'sitting_0.25', 'sitting_0.31',
       'sitting_0.38', 'sitting_0.44', 'sitting_0.47', 'sitting_0.5',
       'sitting_1.0', 'season_-1.0', 'season_-0.33', 'season_0.33',
       'season_1.0', 'age_0.5', 'age_1.0'],
      dtype='object')

In [86]:
#renaming columns:

df_six.rename(columns={
    'fever_-1': 'fever_1yr',
    'fever_0': 'fever_<3mo',
    'fever_1': 'fever_3mo_1yr',
    'alcohol_0.2': 'alcohol_mday',
    'alcohol_0.4': 'alcohol_1day',
    'alcohol_0.6': 'alcohol_mweek',
    'alcohol_0.8': 'alcohol_1week',
    'alcohol_1.0': 'alcohol_negligent',
    'smoking_-1': 'smoke_never',
    'smoking_0': 'smoke_occ',
    'smoking_1': 'smoke_daily',
    'sitting_0.5': 'sitting_<=8hrs',
    'sitting_1.0': 'sitting_>8hrs',
    'season_-1.0': 'season_winter',
    'season_-0.33': 'season_spring',
    'season_0.33': 'season_summer',
    'season_1.0': 'season_fall',
    'age_0.5': 'age_18-27',
    'age_1.0': 'age_28-36'
}, inplace=True)

df_six.columns

Index(['diseases', 'accident', 'surgery', 'diagnosis', 'fever_1yr',
       'fever_<3mo', 'fever_3mo_1yr', 'alcohol_mday', 'alcohol_1day',
       'alcohol_mweek', 'alcohol_1week', 'alcohol_negligent', 'smoke_never',
       'smoke_occ', 'smoke_daily', 'sitting_0.06', 'sitting_0.13',
       'sitting_0.19', 'sitting_0.25', 'sitting_0.31', 'sitting_0.38',
       'sitting_0.44', 'sitting_0.47', 'sitting_<=8hrs', 'sitting_>8hrs',
       'season_winter', 'season_spring', 'season_summer', 'season_fall',
       'age_18-27', 'age_28-36'],
      dtype='object')

In [87]:
df_six.drop(columns=['sitting_0.25', 'sitting_0.31', 'sitting_0.38',
       'sitting_0.44', 'sitting_0.47'], inplace=True)

In [88]:
df_six.drop(columns=['sitting_0.06', 'sitting_0.13',
       'sitting_0.19'], inplace=True)

In [89]:
df_six.head()

diseases  accident  surgery  diagnosis  fever_1yr  fever_<3mo  \
0         0         1        1          0      False        True   
1         1         0        1          1      False        True   
2         1         0        0          0      False        True   
3         0         1        1          0      False        True   
4         1         1        0          1      False        True   

   fever_3mo_1yr  alcohol_mday  alcohol_1day  alcohol_mweek  ...  smoke_occ  \
0          False         False         False          False  ...       True   
1          False         False         False          False  ...      False   
2          False         False         False          False  ...      False   
3          False         False         False          False  ...      False   
4          False         False         False          False  ...      False   

   smoke_daily  sitting_<=8hrs  sitting_>8hrs  season_winter  season_spring  \
0        False           False           True          False           True   
1         True           False          False          False           True   
2        False            True          False          False           True   
3        False           False          False          False           True   
4        False            True          False          False           True   

   season_summer  season_fall  age_18-27  age_28-36  
0          False        False      False       True  
1          False        False      False       True  
2          False        False       True      False  
3          False        False      False       True  
4          False        False      False       True  

[5 rows x 23 columns]

In [90]:
# Assuming df_six is the dataframe you are working with
df_six = df_six.replace({True: 1, False: 0})

# Verify the transformation
print(df_six.head())


   diseases  accident  surgery  diagnosis  fever_1yr  fever_<3mo  \
0         0         1        1          0          0           1   
1         1         0        1          1          0           1   
2         1         0        0          0          0           1   
3         0         1        1          0          0           1   
4         1         1        0          1          0           1   

   fever_3mo_1yr  alcohol_mday  alcohol_1day  alcohol_mweek  ...  smoke_occ  \
0              0             0             0              0  ...          1   
1              0             0             0              0  ...          0   
2              0             0             0              0  ...          0   
3              0             0             0              0  ...          0   
4              0             0             0              0  ...          0   

   smoke_daily  sitting_<=8hrs  sitting_>8hrs  season_winter  season_spring  \
0            0               0       

<ipython-input-90-d88885fa60b2>:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_six = df_six.replace({True: 1, False: 0})


In [91]:
df_six.columns

Index(['diseases', 'accident', 'surgery', 'diagnosis', 'fever_1yr',
       'fever_<3mo', 'fever_3mo_1yr', 'alcohol_mday', 'alcohol_1day',
       'alcohol_mweek', 'alcohol_1week', 'alcohol_negligent', 'smoke_never',
       'smoke_occ', 'smoke_daily', 'sitting_<=8hrs', 'sitting_>8hrs',
       'season_winter', 'season_spring', 'season_summer', 'season_fall',
       'age_18-27', 'age_28-36'],
      dtype='object')

In [92]:
X = df_six.drop("diagnosis", axis=1)
y = df_six["diagnosis"]
print(X.shape, y.shape)

(100, 22) (100,)


# **Logistic Regression**

In [93]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, stratify=y)


In [94]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier

LogisticRegression()

In [95]:
classifier.fit(X_train, y_train)

LogisticRegression()

In [96]:
print(f"Training Data Score: {classifier.score(X_train, y_train)}")
print(f"Testing Data Score: {classifier.score(X_test, y_test)}")

Training Data Score: 0.88
Testing Data Score: 0.84


## **Random Forest Classifier**

In [97]:
from sklearn.ensemble import RandomForestClassifier

In [98]:
rf = RandomForestClassifier(n_estimators=200)
rf = rf.fit(X_train, y_train)
rf.score(X_train, y_train)

1.0

In [99]:
rf.score(X_test, y_test)

0.84

In [100]:
importances = rf.feature_importances_
importances

array([0.06992273, 0.08038781, 0.0730644 , 0.04552058, 0.04446398,
       0.03762583, 0.0047111 , 0.00073958, 0.04772693, 0.05162805,
       0.05356699, 0.0525654 , 0.04774398, 0.04462923, 0.05919266,
       0.03645257, 0.04300281, 0.04492637, 0.00402831, 0.09722651,
       0.03174734, 0.02912687])

# **Decision Tree**

In [101]:
from sklearn import tree

In [102]:
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X_train, y_train)
clf.score(X_test, y_test)

0.8

## **SVC - Serial Vector Machines**

In [103]:
from sklearn.svm import SVC

In [104]:
SVCmodel = SVC(kernel='linear')
SVCmodel

SVC(kernel='linear')

In [105]:
SVCmodel.fit(X_train, y_train)

predictions = SVCmodel.predict(X_test)
predictions

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0])

In [106]:
from sklearn.metrics import classification_report

print(classification_report(y_test, predictions, target_names=['Normal', 'Abnormal']))



              precision    recall  f1-score   support

      Normal       0.88      1.00      0.94        22
    Abnormal       0.00      0.00      0.00         3

    accuracy                           0.88        25
   macro avg       0.44      0.50      0.47        25
weighted avg       0.77      0.88      0.82        25



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


# **Deep Neural Model**

In [107]:
import numpy as np
import tensorflow as ts
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

from sklearn.preprocessing import LabelEncoder


In [108]:
df

season   age  diseases  accident  surgery  fever  alcohol  smoking  \
0    -0.33  0.69         0         1        1      0      0.8        0   
1    -0.33  0.94         1         0        1      0      0.8        1   
2    -0.33  0.50         1         0        0      0      1.0       -1   
3    -0.33  0.75         0         1        1      0      1.0       -1   
4    -0.33  0.67         1         1        0      0      0.8       -1   
..     ...   ...       ...       ...      ...    ...      ...      ...   
95   -1.00  0.67         1         0        0      0      1.0       -1   
96   -1.00  0.61         1         0        0      0      0.8        0   
97   -1.00  0.67         1         1        1      0      1.0       -1   
98   -1.00  0.64         1         0        1      0      1.0        0   
99   -1.00  0.69         0         1        1      0      0.6       -1   

    sitting  diagnosis  
0      0.88          0  
1      0.31          1  
2      0.50          0  
3      0.38          0  
4      0.50          1  
..      ...        ...  
95     0.50          0  
96     0.50          0  
97     0.31          0  
98     0.19          0  
99     0.19          0  

[100 rows x 10 columns]

In [109]:
df_one = pd.get_dummies(df, columns=['fever'], prefix = ['fever'])
df_two = pd.get_dummies(df_one, columns=['alcohol'], prefix = ['alcohol'])
df_three = pd.get_dummies(df_two, columns=['smoking'], prefix = ['smoking'])

In [110]:
df_three.loc[df_three['sitting'] > 0.5, 'sitting'] = 1

In [111]:
df_three.loc[df_three['sitting'] <= 0.5, 'sitting'] = 0.5

In [112]:
df_four = pd.get_dummies(df_three, columns=['sitting'], prefix = ['sitting'])

In [113]:
df_five = pd.get_dummies(df_four, columns=['season'], prefix = ['season'])

In [114]:
df_five.loc[df_five['age'] > 0.5, 'age'] = 1

In [115]:
df_five.loc[df_five['age'] <= 0.5, 'age'] = 0.5

In [116]:
df_six = pd.get_dummies(df_five, columns=['age'], prefix = ['age'])
df_six.head()

diseases  accident  surgery  diagnosis  fever_-1  fever_0  fever_1  \
0         0         1        1          0     False     True    False   
1         1         0        1          1     False     True    False   
2         1         0        0          0     False     True    False   
3         0         1        1          0     False     True    False   
4         1         1        0          1     False     True    False   

   alcohol_0.2  alcohol_0.4  alcohol_0.6  ...  smoking_0  smoking_1  \
0        False        False        False  ...       True      False   
1        False        False        False  ...      False       True   
2        False        False        False  ...      False      False   
3        False        False        False  ...      False      False   
4        False        False        False  ...      False      False   

   sitting_0.5  sitting_1.0  season_-1.0  season_-0.33  season_0.33  \
0        False         True        False          True        False   
1         True        False        False          True        False   
2         True        False        False          True        False   
3         True        False        False          True        False   
4         True        False        False          True        False   

   season_1.0  age_0.5  age_1.0  
0       False    False     True  
1       False    False     True  
2       False     True    False  
3       False    False     True  
4       False    False     True  

[5 rows x 23 columns]

In [117]:
# Assuming df_six is the dataframe you are working with
df_six = df_six.replace({True: 1, False: 0})

# Verify the transformation
print(df_six.head())


   diseases  accident  surgery  diagnosis  fever_-1  fever_0  fever_1  \
0         0         1        1          0         0        1        0   
1         1         0        1          1         0        1        0   
2         1         0        0          0         0        1        0   
3         0         1        1          0         0        1        0   
4         1         1        0          1         0        1        0   

   alcohol_0.2  alcohol_0.4  alcohol_0.6  ...  smoking_0  smoking_1  \
0            0            0            0  ...          1          0   
1            0            0            0  ...          0          1   
2            0            0            0  ...          0          0   
3            0            0            0  ...          0          0   
4            0            0            0  ...          0          0   

   sitting_0.5  sitting_1.0  season_-1.0  season_-0.33  season_0.33  \
0            0            1            0             1         

<ipython-input-117-d88885fa60b2>:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_six = df_six.replace({True: 1, False: 0})


In [118]:
print(df_six.dtypes)
print(df_six.values)

diseases        int64
accident        int64
surgery         int64
diagnosis       int64
fever_-1        int64
fever_0         int64
fever_1         int64
alcohol_0.2     int64
alcohol_0.4     int64
alcohol_0.6     int64
alcohol_0.8     int64
alcohol_1.0     int64
smoking_-1      int64
smoking_0       int64
smoking_1       int64
sitting_0.5     int64
sitting_1.0     int64
season_-1.0     int64
season_-0.33    int64
season_0.33     int64
season_1.0      int64
age_0.5         int64
age_1.0         int64
dtype: object
[[0 1 1 ... 0 0 1]
 [1 0 1 ... 0 0 1]
 [1 0 0 ... 0 1 0]
 ...
 [1 1 1 ... 0 0 1]
 [1 0 1 ... 0 0 1]
 [0 1 1 ... 0 0 1]]


In [119]:
X = df_six.drop("diagnosis", axis=1)
y = df_six["diagnosis"]

In [120]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

In [121]:
label_encoder = LabelEncoder()
label_encoder.fit(y_train)
encoded_y = label_encoder.transform(y_train)

In [122]:
for label, original_class in zip(encoded_y, y):
    print(original_class)
    print(label)

0
0
1
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
1
1
0
1
0
0
0
0
1
0
0
0
0
0
1
0
1
1
0
1
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
1
0
1
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0


In [123]:
from keras.utils import to_categorical
one_hot_y = to_categorical(encoded_y)
one_hot_y

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.

In [124]:
model = Sequential()
model.add(Dense(units=6, activation='relu', input_dim=22))
model.add(Dense(units=6, activation='relu'))
model.add(Dense(units=2, activation='softmax'))
model.summary()

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                      │ (None, 6)                   │             138 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_4 (Dense)                      │ (None, 6)                   │              42 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_5 (Dense)                      │ (None, 2)                   │              14 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 194 (776.00 B)

 Trainable params: 194 (776.00 B)

 Non-trainable params: 0 (0.00 B)

In [125]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [126]:
model.fit(X_train, one_hot_y, epochs=500, shuffle=True, verbose=2)

Epoch 1/500
3/3 - 2s - 691ms/step - accuracy: 0.1200 - loss: 1.3066
Epoch 2/500
3/3 - 0s - 14ms/step - accuracy: 0.1200 - loss: 1.2369
Epoch 3/500
3/3 - 0s - 23ms/step - accuracy: 0.1200 - loss: 1.1682
Epoch 4/500
3/3 - 0s - 27ms/step - accuracy: 0.1467 - loss: 1.1058
Epoch 5/500
3/3 - 0s - 28ms/step - accuracy: 0.1467 - loss: 1.0518
Epoch 6/500
3/3 - 0s - 14ms/step - accuracy: 0.1867 - loss: 0.9977
Epoch 7/500
3/3 - 0s - 31ms/step - accuracy: 0.2000 - loss: 0.9483
Epoch 8/500
3/3 - 0s - 23ms/step - accuracy: 0.2133 - loss: 0.9025
Epoch 9/500
3/3 - 0s - 24ms/step - accuracy: 0.2267 - loss: 0.8598
Epoch 10/500
3/3 - 0s - 42ms/step - accuracy: 0.3067 - loss: 0.8224
Epoch 11/500
3/3 - 0s - 26ms/step - accuracy: 0.3467 - loss: 0.7859
Epoch 12/500
3/3 - 0s - 27ms/step - accuracy: 0.3867 - loss: 0.7518
Epoch 13/500
3/3 - 0s - 50ms/step - accuracy: 0.4533 - loss: 0.7227
Epoch 14/500
3/3 - 0s - 46ms/step - accuracy: 0.5333 - loss: 0.6936
Epoch 15/500
3/3 - 0s - 51ms/step - accuracy: 0.5867 - l

In [127]:
label_encoder2 = LabelEncoder()
label_encoder2.fit(y_test)
encoded_y_test = label_encoder.transform(y_test)

for label, original_class in zip(encoded_y_test, y):
    print(original_class)
    print(label)

0
0
1
0
0
1
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
1
0
0
0
1
0
0
0
0
0
0
1
1
0
0
0


In [128]:
one_hot_y_test = to_categorical(encoded_y_test)
one_hot_y_test

array([[1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.]])

In [129]:
model.fit(X_test, one_hot_y_test, epochs=500, shuffle=True, verbose=2)

Epoch 1/500
1/1 - 0s - 27ms/step - accuracy: 0.8000 - loss: 1.0048
Epoch 2/500
1/1 - 0s - 57ms/step - accuracy: 0.8000 - loss: 0.9940
Epoch 3/500
1/1 - 0s - 27ms/step - accuracy: 0.8000 - loss: 0.9749
Epoch 4/500
1/1 - 0s - 56ms/step - accuracy: 0.8400 - loss: 0.9498
Epoch 5/500
1/1 - 0s - 26ms/step - accuracy: 0.8400 - loss: 0.9203
Epoch 6/500
1/1 - 0s - 20ms/step - accuracy: 0.8400 - loss: 0.8878
Epoch 7/500
1/1 - 0s - 20ms/step - accuracy: 0.8400 - loss: 0.8532
Epoch 8/500
1/1 - 0s - 21ms/step - accuracy: 0.8400 - loss: 0.8161
Epoch 9/500
1/1 - 0s - 20ms/step - accuracy: 0.8400 - loss: 0.7783
Epoch 10/500
1/1 - 0s - 23ms/step - accuracy: 0.8400 - loss: 0.7389
Epoch 11/500
1/1 - 0s - 20ms/step - accuracy: 0.8400 - loss: 0.6993
Epoch 12/500
1/1 - 0s - 23ms/step - accuracy: 0.8400 - loss: 0.6603
Epoch 13/500
1/1 - 0s - 21ms/step - accuracy: 0.8400 - loss: 0.6223
Epoch 14/500
1/1 - 0s - 20ms/step - accuracy: 0.8400 - loss: 0.5852
Epoch 15/500
1/1 - 0s - 58ms/step - accuracy: 0.8800 - lo

In [130]:
import numpy as np

new_data = np.array([[1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0]])
print(model.predict(new_data))

predictions = model.predict(new_data)
predicted_class = np.argmax(predictions, axis=1)
print(predicted_class)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
[[9.9947304e-01 5.2697241e-04]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step
[0]


In [131]:
df.columns

Index(['season', 'age', 'diseases', 'accident', 'surgery', 'fever', 'alcohol',
       'smoking', 'sitting', 'diagnosis'],
      dtype='object')

In [132]:
df_six.columns

Index(['diseases', 'accident', 'surgery', 'diagnosis', 'fever_-1', 'fever_0',
       'fever_1', 'alcohol_0.2', 'alcohol_0.4', 'alcohol_0.6', 'alcohol_0.8',
       'alcohol_1.0', 'smoking_-1', 'smoking_0', 'smoking_1', 'sitting_0.5',
       'sitting_1.0', 'season_-1.0', 'season_-0.33', 'season_0.33',
       'season_1.0', 'age_0.5', 'age_1.0'],
      dtype='object')

In [133]:
output_file = 'male_fertility_data.csv'  # Specify your desired output file name
df_six.to_csv(output_file, index=False)